machine:
  python:
    version: 3.6.1

dependencies:
  pre:
    - "pip3 install -U -r requirements/tests.txt"
    - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh"
    - "bash miniconda.sh -b -p $HOME/miniconda"

test:
  override:
    - |
        git config --global user.name "Anthony Scopatz"
        git config --global user.email scopatz@gmail.com
        py.test -v ./tests/
