machine:
  environment:
      PATH: /home/ubuntu/miniconda/bin:$PATH

dependencies:
  pre:
    - "wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh"
    - "bash miniconda.sh -b -p $HOME/miniconda"
    - "conda install -f requirements/tests.txt"

test:
  override:
    - |
        git config --global user.name "Anthony Scopatz"
        git config --global user.email scopatz@gmail.com
        py.test -v ./tests/
