machine:
  python:
    version: 3.6.1

dependencies:
  pre:
    - "pip3 install -U -r requirements/tests.txt"

test:
  override:
    - |
        git config --global user.name "Anthony Scopatz"
        git config --global user.email scopatz@gmail.com
        py.test -v ./tests/

